name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Ejemplo Modulo 3.4
      id: ejemplo-modulo-3-4
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Ejemplo Modulo 3.4
        setup-command: npm install
        command: npm test
        timeout: 5
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        EJEMPLO-MODULO-3-4_RESULTS: "${{steps.ejemplo-modulo-3-4.outputs.result}}"
      with:
        runners: ejemplo-modulo-3-4
